version: '2.0'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/usr/src/app
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
