version: '2.0'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/code
    # environment:
    #   FLASK_ENV: development
  mongodb_container:
    image: mongo:latest
    # environment:
    # // enables auth
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
